=== Tachyonite/Pawnmorpher/Schemas/AspectDef.xsd
<?xml version="1.0" encoding="utf-8" ?>

<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:include schemaLocation="include/CommonComplex.xsd" />
    <xs:element name="Defs">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Pawnmorph.AspectDef" type="AspectDef" minOccurs="1" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="AspectDef">
        <xs:all>
            <xs:element name="defName" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="priority" type="xs:int" minOccurs="0" maxOccurs="1" />
            <xs:element name="label" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="aspectType" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="labelColor" type="Color" minOccurs="0" maxOccurs="1" />
            <xs:element name="removedByReverter" type="xs:boolean" minOccurs="0" maxOccurs="1" />
            <xs:element name="transferToAnimal" type="xs:boolean" minOccurs="0" />
            <xs:element name="scenarioCanAdd" type="xs:boolean" minOccurs="0" />
            <xs:element name="stages" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="li" type="AspectStage" minOccurs="1" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="nullifiedThoughts" type="ListOfStrings" minOccurs="0" />
            <xs:element name="conflictingAspects" type="ListOfStrings" minOccurs="0"/>
            <xs:element name="requiredTraits" type="ListOfStrings" minOccurs="0"/>
            <xs:element name="conflictingTraits" type="ListOfStrings" minOccurs="0"/>
        </xs:all>
        <xs:attribute name="ParentName" type="xs:string" use="optional" />
        <xs:attribute name="Abstract" type="xs:boolean" use="optional" />
        <xs:attribute name="Name" type="xs:string" use="optional" />
    </xs:complexType>

    <xs:complexType name="AspectStage">
        <xs:all>
            <xs:element name="label" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="modifier" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="1" />
            <xs:element name="labelColor" type="Color" minOccurs="0" maxOccurs="1" />
            <xs:element name="mentalBreakMtbDays" minOccurs="0" maxOccurs="1" />
            <xs:element name="isBad" type="xs:boolean" minOccurs="0"/>
            <xs:element name="capMods" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="li" type="PawnCapacityModifier" minOccurs="1" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="skillMods" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="li" type="SkillMod" minOccurs="1" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="statOffsets" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:any minOccurs="1" maxOccurs="unbounded" processContents="lax" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="mentalStateGivers" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="li" type="MentalStateGiver" minOccurs="1" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="productionBoosts" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="li" type="ProductionBoost" minOccurs="1" maxOccurs="1" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="nullifiedThoughts" type="ListOfStrings" minOccurs="0"/>
            <xs:element name="messageText" type="xs:string" minOccurs="0"/>
            <xs:element name="messageDef" type="xs:string" minOccurs="0"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="PawnCapacityModifier">
        <xs:sequence>
            <xs:element name="capacity" type="xs:string" minOccurs="1" maxOccurs="1" />
            <xs:element name="setMax" type="xs:float" minOccurs="0" maxOccurs="1" />
            <xs:element name="postFactor" type="xs:float" minOccurs="0" maxOccurs="1" />
            <xs:element name="offset" type="xs:float" minOccurs="0" maxOccurs="1" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="SkillMod">
        <xs:sequence>
            <xs:element name="skillDef" type="xs:string" minOccurs="1" maxOccurs="1" />
            <xs:element name="addedXp" type="xs:float" minOccurs="0" maxOccurs="1" />
            <xs:element name="passionOffset" type="xs:int" minOccurs="0" maxOccurs="1" />
            <xs:element name="forcedPassion" type="Passion" minOccurs="0" maxOccurs="1" />
        </xs:sequence>
    </xs:complexType>


    <xs:complexType name="MentalStateGiver">
        <xs:sequence>
            <xs:element name="mentalState" type="xs:string" minOccurs="1" maxOccurs="1" />
            <xs:element name="mtbDays" type="xs:float" minOccurs="1" maxOccurs="1" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ProductionBoost">
        <xs:sequence>
            <xs:element name="productionBoost" type="xs:float" minOccurs="1" maxOccurs="1" />
            <xs:element name="hediffFilter" type="HediffFilter" minOccurs="0" maxOccurs="1" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="HediffFilter">
        <xs:sequence>
            <xs:element name="isBlackList" type="xs:boolean" minOccurs="0" maxOccurs="1" />
            <xs:element name="filterList" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="li" type="xs:string" minOccurs="1" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="Passion">
        <xs:restriction base="xs:string">
            <xs:enumeration value="None" />
            <xs:enumeration value="Minor" />
            <xs:enumeration value="Major" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="Color">
        <xs:restriction base="xs:string">
            <xs:pattern value="\([0-9]{1,3},[0-9]{1,3},[0-9]{1,3}\)" />
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== Tachyonite/Pawnmorpher/1.2/Defs/Morphs/Panther/Panther_Aspects.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../Schemas/AspectDef.xsd">
	<Pawnmorph.AspectDef>
		<defName>PantherAspect</defName>
		<label>instictive predator</label>
		<description>The blood of a panther runs through this pawn's veins. Their senses are keener, their body more agile, and their claws sharper. They are the perfect predator.</description>
		<scenarioCanAdd>true</scenarioCanAdd>
		<stages>
			<li>
				<label>instictive predator</label>
				<description>The blood of a panther runs through [PAWN_nameDef]'s veins. [PAWN_possessive] senses are keener, [PAWN_possessive] body more agile, and [PAWN_possessive] claws sharper. [PAWN_pronoun] is the perfect predator.</description>
				<capMods>
					<li>
						<capacity>Moving</capacity>
						<offset>0.05</offset>
					</li>
					<li>
						<capacity>Sight</capacity>
						<offset>0.05</offset>
					</li>
					<li>
						<capacity>Hearing</capacity>
						<offset>0.05</offset>
					</li>
				</capMods>
				<statOffsets>
					<MeleeDodgeChance>20</MeleeDodgeChance>
					<HuntingStealth>0.15</HuntingStealth>
				</statOffsets>
			</li>
		</stages>
	</Pawnmorph.AspectDef>
</Defs>

=== Tachyonite/Pawnmorpher/1.4/Defs/Aspects/Aspects_FormerHuman.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../Schemas/AspectDef.xsd">
	<Pawnmorph.AspectDef>
		<defName>PrimalWish</defName>
		<label>primal wish</label>
		<description>This pawn desires a simple life. So simple, some might comment, that it is suited more for an animal than a human. Indeed, this pawn does envy animals, and would rather be one than human.</description>
		<scenarioCanAdd>true</scenarioCanAdd>
		<transferToAnimal>true</transferToAnimal>
		<stages>
			<li>
				<label>primal wish</label>
				<description>[PAWN_nameDef] desires a simple life. So simple, some might comment, that it is suited more for an animal than a human. Indeed, [PAWN_nameDef] does envy animals, and would rather be one than human.</description>
				<messageText>Upon becoming a morph, [PAWN_nameDef] has gained a 'primal wish'. [PAWN_pronoun] might want to go even further with their mutations...</messageText>
			</li>
		</stages>
	</Pawnmorph.AspectDef>
	<Pawnmorph.AspectDef>
		<defName>Beastmaster</defName>
		<label>beastmaster</label>
		<description>This pawn likes the company of animals who were once people, and feels more at ease being around them.</description>
		<scenarioCanAdd>true</scenarioCanAdd>
		<stages>
			<li>
				<label>beastmaster</label>
				<description>[PAWN_nameDef] likes the company of animals who were once people, and feels more at ease being around them.</description>
			</li>
		</stages>
	</Pawnmorph.AspectDef>
</Defs>
