=== Tachyonite/Pawnmorpher/Schemas/MorphDef.xsd
<?xml version="1.0" encoding="Windows-1252" ?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:include schemaLocation="include/Recipe.xsd" />
	<xs:element name="Defs">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Pawnmorph.MorphDef" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:all>
							<xs:element name="defName" type="xs:string" minOccurs="0" maxOccurs="1" />
							<xs:element name="label" type="xs:string" minOccurs="0" maxOccurs="1" />
							<xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="1" />
							<xs:element name="race" type="xs:string" minOccurs="0" maxOccurs="1" />
							<xs:element name="group" type="MorphGroups" minOccurs="0" maxOccurs="1" />
							<xs:element name="associatedAnimals" type="ListOfStrings" minOccurs="0" maxOccurs="1" />
							<xs:element name="categories" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element maxOccurs="unbounded" name="li" type="MorphCategory" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="raceSettings" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:all>
										<xs:element name="statModifiers" type="StatModifiersList" minOccurs="0" maxOccurs="1" />
										<xs:element name="thoughtSettings" type="HybridThoughtSettings" maxOccurs="1" minOccurs="0" />
										<xs:element name="graphicsSettings" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="skinColorOverride" type="xs:string" minOccurs="0" maxOccurs="1" />
													<xs:element name="skinColorOverrideSecond" type="xs:string" minOccurs="0" maxOccurs="1" />
													<xs:element name="femaleSkinColorOverride" type="xs:string" minOccurs="0" maxOccurs="1" />
													<xs:element name="femaleSkinColorOverrideSecond" type="xs:string" minOccurs="0" maxOccurs="1" />
													<xs:element name="hairColorOverride" type="xs:string" minOccurs="0" maxOccurs="1" />
													<xs:element name="hairColorOverrideSecond" type="xs:string" minOccurs="0" maxOccurs="1" />
													<xs:element name="femaleHairColorOverride" type="xs:string" minOccurs="0" maxOccurs="1" />
													<xs:element name="femaleHairColorOverrideSecond" type="xs:string" minOccurs="0" maxOccurs="1" />
													<xs:element name="customDrawSize" type="xs:string" minOccurs="0" maxOccurs="1" />
													<xs:element name="customHeadDrawSize" type="xs:string" minOccurs="0" maxOccurs="1" />
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="traitSettings" type="TraitSettings" minOccurs="0" maxOccurs="1" />
										<xs:element name="explicitHybridRace" type="xs:string" minOccurs="0" maxOccurs="1" />
										<xs:element name="transferHumanBodyAddons" type="xs:boolean" minOccurs="0" maxOccurs="1" />
										<xs:element name="requiredMutations" type="ListOfStrings" minOccurs="0" maxOccurs="1" />
									</xs:all>
								</xs:complexType>
							</xs:element>
							<xs:element name="noInjector" type="xs:boolean" minOccurs="0" />
							<xs:element name="injectorDef" type="xs:string" minOccurs="0" />
							<xs:element name="transformSettings" type="TransformationSettings" minOccurs="0" maxOccurs="1" />
							<xs:element name="fullTransformation" type="xs:string" minOccurs="0" />
							<xs:element name="partialTransformation" type="xs:string" minOccurs="0"/>
							<xs:element name="addedAspects" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="li" type="AddedAspect" minOccurs="1" maxOccurs="unbounded" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="classification" type="AnimalClassification" minOccurs="0"/>
							<xs:element name="injectorProperties" type="MorphInjectorProperties" minOccurs="0" nillable="true" />
							<xs:element name="fullTfHediffProps" type="MorphHediffProperties" minOccurs="0" nillable="true" />
							<xs:element name="partialTfHediffProps" type="MorphHediffProperties" minOccurs="0" nillable="true" />
						</xs:all>
						<xs:attribute name="ParentName" type="xs:string" use="optional" />
						<xs:attribute name="Name" type="xs:string" use="optional" />
						<xs:attribute name="Abstract" type="xs:boolean" use="optional" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="StatModifiersList">
		<xs:sequence>
			<xs:element name="li" type="StatModifier" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="HybridThoughtSettings">
		<xs:sequence>
			<xs:element name="replacerList" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="li" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="original" type="xs:string" />
									<xs:element name="replacer" type="xs:string" />
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="ateAnimalThought" minOccurs="0" maxOccurs="1" type="AteThought"></xs:element>
			<xs:element name="butcheredAnimalThought" type="ButcherThought" minOccurs="0" maxOccurs="1" />
			<xs:element name="suppressHumanlikeCannibalThoughts" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="canEatRaw" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="thoughtsBlackList" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="li" type="xs:string" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="ateThoughtsSpecifics" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="li" type="AteThought" minOccurs="1" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="butcherThoughtsSpecifics" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="li" maxOccurs="unbounded" type="ButcherThought" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="AteThought">
		<xs:sequence>
			<xs:element name="thought" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="thoughtCannibal" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="ingredientThought" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="ingredientThoughtCannibal" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="raceList" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="li" type="xs:string" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ButcherThought">
		<xs:sequence>
			<xs:element name="thought" type="xs:string" />
			<xs:element name="knowThought" type="xs:string" />
			<xs:element name="raceList" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="li" type="xs:string" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="TransformationSettings">
		<xs:sequence>
			<xs:element name="transformationTale" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="transformationMessageID" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="messageDef" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="transformationMemory" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="revertedMemory" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="revertedMemoryFurry" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="revertedMemoryBP" type="xs:string" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="TraitSettings">
		<xs:sequence>
			<xs:element name="forcedTraits" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="li" minOccurs="1" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="chance" type="xs:float" minOccurs="0" maxOccurs="1" />
									<xs:element name="commonalityMale" type="xs:float" minOccurs="0" maxOccurs="1" />
									<xs:element name="commonalityFemale" type="xs:float" minOccurs="0" maxOccurs="1" />
									<xs:element name="defName" type="xs:string" maxOccurs="1" minOccurs="1" />
									<xs:element name="degree" type="xs:int" maxOccurs="1" minOccurs="0" />
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="AddedAspect">
		<xs:sequence>
			<xs:element name="def" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="keepOnReversion" type="xs:boolean" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="StageAlert">
		<xs:all>
			<xs:element name="letterLabelText" type="xs:string" minOccurs="0" />
			<xs:element name="letterContentText" type="xs:string" minOccurs="0" />
			<xs:element name="letterDef" type="xs:string" minOccurs="0" />
		</xs:all>
	</xs:complexType>

	<xs:complexType name="TFMiscSettings">
		<xs:all>
			<xs:element name="tfTale" type="xs:string" minOccurs="0" />
			<xs:element name="warningLabelOverride" type="xs:string" minOccurs="0" />
			<xs:element name="warningContentOverride" type="xs:string" minOccurs="0" />
			<xs:element name="warningLetterDef" type="xs:string" minOccurs="0" />
			<xs:element name="displayWarning" type="xs:boolean" minOccurs="0" />
			<xs:element name="forcedSapience" type="xs:float" minOccurs="0" />
		</xs:all>
	</xs:complexType>

	<xs:complexType name="MorphHediffProperties">
		<xs:all>
			<xs:element name="label" type="xs:string" minOccurs="0" />
			<xs:element name="description" type="xs:string" minOccurs="0" />
			<xs:element name="labelColor" type="Color" minOccurs="0" />
			<xs:element name="MutagenDef" type="xs:string" minOccurs="0" />
			<xs:element name="tfAlert" type="StageAlert" minOccurs="0" />
			<xs:element name="removeNonMorphPartChance" type="xs:float" minOccurs="0" />
			<xs:element name="tfSettings" type="TFMiscSettings" minOccurs="0" />
			<xs:element name="hungerRateFactor" type="xs:float" minOccurs="0" />
			<xs:element name="capMods" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:any processContents="lax" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>

			<xs:element name="aspectGivers" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="li" minOccurs="1" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:any processContents="lax" maxOccurs="unbounded" />
								</xs:sequence>
								<xs:attribute name="Class" use="required" type="xs:string" />
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:all>
	</xs:complexType>

	<xs:complexType name="MorphInjectorProperties">
		<xs:all>
			<xs:element name="label" type="xs:string" minOccurs="0" />
			<xs:element name="statBases" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:any processContents="lax" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="workAmount" type="xs:positiveInteger" minOccurs="0" />
			<xs:element name="techLevel" type="TechLevel" minOccurs="0" />
			<xs:element name="traderTags" type="ListOfStrings" minOccurs="0" />
			<xs:element name="description" type="xs:string" minOccurs="0" />
			<xs:element name="useDefaultTags" type="xs:boolean" minOccurs="0" />
			<xs:element name="costList" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:any processContents="lax" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="slurryCost" type="xs:positiveInteger" minOccurs="0" />
			<xs:element name="neutroamineCost" type="xs:positiveInteger" minOccurs="0" />
			<xs:element name="mutaniteCost" type="xs:positiveInteger" minOccurs="0" />
			<xs:element name="outcomeDoers" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="li" minOccurs="1" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:any processContents="lax" maxOccurs="unbounded" />
								</xs:sequence>
								<xs:attribute name="Class" use="required" type="xs:string" />
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>

			<xs:element name="graphicData" type="GraphicData" minOccurs="0" />

			<xs:element name="recipeMaker" type="RecipeMaker" minOccurs="0" />
		</xs:all>
	</xs:complexType>
</xs:schema>

=== Tachyonite/Pawnmorpher/1.3/Defs/MorphsAndMutationDefs/Animal/PawFooted/Carnivora/Canid/Lupine/Arctic Wolf/ArcticWolf_MorphDef.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../../../../Schemas/MorphDef.xsd">
	<Pawnmorph.MorphDef ParentName="WolfMorphBase">
		<defName>ArcticWolfMorph</defName>
		<label>arcticwolfmorph</label>
		<race>Wolf_Arctic</race>
		<categories>
			<li>Cold</li>
		</categories>
		<fullTransformation>PawnmorphArcticWolfTF</fullTransformation>
		<partialTransformation>PawnmorphArcticWolfTFPartial</partialTransformation>
		<raceSettings>
			<graphicsSettings>
				<skinColorOverride>(249,242,221)</skinColorOverride>
			</graphicsSettings>
		</raceSettings>
	</Pawnmorph.MorphDef>
</Defs>

=== Tachyonite/Pawnmorpher/1.4/Defs/MorphsAndMutationDefs/Animal/Ungulate/EvenToedUngulate/Caprid/Goat/Goat_MorphDef.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../Schemas/MorphDef.xsd">
	<Pawnmorph.MorphDef ParentName="CapridMorph">
		<defName>GoatMorph</defName>
		<label>goatmorph</label>
		<description>With a beard and cuboid pupils, goatmorphs are a 'farm'-type morph who are rowdy in combat. Female goatmorphs can produce milk.</description>
		<race>Goat</race>
		<categories>
			<li>Domestic</li>
		</categories>
		<injectorProperties></injectorProperties>
		<fullTransformation>PawnmorphGoatTF</fullTransformation>
		<partialTransformation>PawnmorphGoatTFPartial</partialTransformation>
		<raceSettings>
			<graphicsSettings>
				<skinColorOverride>(220,220,220)</skinColorOverride>
			</graphicsSettings>
		</raceSettings>
		<transformSettings>
			<transformationMemory>GoatTransformationMemory</transformationMemory>
			<revertedMemory>GoatRevertedMemory</revertedMemory>
		</transformSettings>
	</Pawnmorph.MorphDef>
</Defs>

=== Tachyonite/Pawnmorpher/Defs/Morphs/Alpaca/Alpaca_MorphDef.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../Schemas/MorphDef.xsd">
	<Pawnmorph.MorphDef ParentName="HerdMorph">
		<defName>AlpacaMorph</defName>
		<label>alpacamorph</label>
		<description>Alpacamorphs are rather woolly herbivorous humanoids who often have hooves. They produce good amounts of soft wool, which they can shave off themselves... and they don't need your help, thank you.</description>
		<race>Alpaca</race>
		<classification>Camelid</classification>
		<categories>
			<li>Temperate</li>
			<li>Tropical</li>
			<li>Farm</li>
			<li>Production</li>
		</categories>
		<fullTransformation>PawnmorphAlpacaTF</fullTransformation>
		<partialTransformation>PawnmorphAlpacaTFPartial</partialTransformation>
		<raceSettings>
			<graphicsSettings>
				<skinColorOverride>(223,188,126)</skinColorOverride>
			</graphicsSettings>
		</raceSettings>
		<transformSettings>
			<transformationMemory>AlpacaTransformationMemory</transformationMemory>
			<revertedMemory>AlpacaRevertedMemory</revertedMemory>
		</transformSettings>
	</Pawnmorph.MorphDef>
</Defs>

=== Tachyonite/Pawnmorpher/1.4/Defs/MorphsAndMutationDefs/Animal/PawFooted/Carnivora/Feline/Pantherine/Panther/Panther_MorphDef.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../../../../Schemas/MorphDef.xsd">
	<Pawnmorph.MorphDef ParentName="PantherineMorph">
		<defName>PantherMorph</defName>
		<label>panthermorph</label>
		<description>A large catlike morph covered in a sleek black fur. They are natural predators, and have the agility and killing power to prove it.</description>
		<race>Panther</race>
		<categories>
			<li>Tropical</li>
		</categories>
		<fullTransformation>PawnmorphPantherTF</fullTransformation>
		<partialTransformation>PawnmorphPantherTFPartial</partialTransformation>
		<addedAspects>
			<li>
				<def>PantherAspect</def>
				<keepOnReversion>false</keepOnReversion>
			</li>
		</addedAspects>
		<raceSettings>
			<graphicsSettings>
				<skinColorOverride>(60,60,60)</skinColorOverride>
			</graphicsSettings>
		</raceSettings>
		<transformSettings>
			<transformationMemory>PantherTransformationMemory</transformationMemory>
			<revertedMemory>PantherRevertedMemory</revertedMemory>
		</transformSettings>
	</Pawnmorph.MorphDef>
</Defs>

=== Tachyonite/Pawnmorpher/1.2/Defs/Morphs/Iguana/Iguana_MorphDef.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../Schemas/MorphDef.xsd">
	<Pawnmorph.MorphDef ParentName="SensitiveFoodMorph">
		<defName>IguanaMorph</defName>
		<label>iguanamorph</label>
		<description>A scaly reptile morph with traits similar to that of an iguana.</description>
		<race>Iguana</race>
		<classification>Reptile</classification>
		<categories>
			<li>Arid</li>
			<li>Reptile</li>
		</categories>
		<fullTransformation>PawnmorphIguanaTF</fullTransformation>
		<partialTransformation>PawnmorphIguanaTFPartial</partialTransformation>
		<raceSettings>
			<graphicsSettings>
				<skinColorOverride>(101,115,57)</skinColorOverride>
			</graphicsSettings>
		</raceSettings>
		<transformSettings>
			<transformationMemory>IguanaTransformationMemory</transformationMemory>
			<revertedMemory>IguanaRevertedMemory</revertedMemory>
		</transformSettings>
	</Pawnmorph.MorphDef>
</Defs>
