=== Tachyonite/Pawnmorpher/Schemas/MorphDef.xsd
<?xml version="1.0" encoding="Windows-1252" ?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:include schemaLocation="include/Recipe.xsd" />
	<xs:element name="Defs">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Pawnmorph.MorphDef" minOccurs="1" maxOccurs="unbounded">
					<xs:complexType>
						<xs:all>
							<xs:element name="defName" type="xs:string" minOccurs="0" maxOccurs="1" />
							<xs:element name="label" type="xs:string" minOccurs="0" maxOccurs="1" />
							<xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="1" />
							<xs:element name="race" type="xs:string" minOccurs="0" maxOccurs="1" />
							<xs:element name="group" type="MorphGroups" minOccurs="0" maxOccurs="1" />
							<xs:element name="associatedAnimals" type="ListOfStrings" minOccurs="0" maxOccurs="1" />
							<xs:element name="categories" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element maxOccurs="unbounded" name="li" type="MorphCategory" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="raceSettings" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:all>
										<xs:element name="statModifiers" type="StatModifiersList" minOccurs="0" maxOccurs="1" />
										<xs:element name="thoughtSettings" type="HybridThoughtSettings" maxOccurs="1" minOccurs="0" />
										<xs:element name="graphicsSettings" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="skinColorOverride" type="xs:string" minOccurs="0" maxOccurs="1" />
													<xs:element name="skinColorOverrideSecond" type="xs:string" minOccurs="0" maxOccurs="1" />
													<xs:element name="femaleSkinColorOverride" type="xs:string" minOccurs="0" maxOccurs="1" />
													<xs:element name="femaleSkinColorOverrideSecond" type="xs:string" minOccurs="0" maxOccurs="1" />
													<xs:element name="hairColorOverride" type="xs:string" minOccurs="0" maxOccurs="1" />
													<xs:element name="hairColorOverrideSecond" type="xs:string" minOccurs="0" maxOccurs="1" />
													<xs:element name="femaleHairColorOverride" type="xs:string" minOccurs="0" maxOccurs="1" />
													<xs:element name="femaleHairColorOverrideSecond" type="xs:string" minOccurs="0" maxOccurs="1" />
													<xs:element name="customDrawSize" type="xs:string" minOccurs="0" maxOccurs="1" />
													<xs:element name="customHeadDrawSize" type="xs:string" minOccurs="0" maxOccurs="1" />
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="traitSettings" type="TraitSettings" minOccurs="0" maxOccurs="1" />
										<xs:element name="explicitHybridRace" type="xs:string" minOccurs="0" maxOccurs="1" />
										<xs:element name="transferHumanBodyAddons" type="xs:boolean" minOccurs="0" maxOccurs="1" />
										<xs:element name="requiredMutations" type="ListOfStrings" minOccurs="0" maxOccurs="1" />
									</xs:all>
								</xs:complexType>
							</xs:element>
							<xs:element name="noInjector" type="xs:boolean" minOccurs="0" />
							<xs:element name="injectorDef" type="xs:string" minOccurs="0" />
							<xs:element name="transformSettings" type="TransformationSettings" minOccurs="0" maxOccurs="1" />
							<xs:element name="fullTransformation" type="xs:string" minOccurs="0" />
							<xs:element name="partialTransformation" type="xs:string" minOccurs="0"/>
							<xs:element name="addedAspects" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="li" type="AddedAspect" minOccurs="1" maxOccurs="unbounded" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="classification" type="AnimalClassification" minOccurs="0"/>
							<xs:element name="injectorProperties" type="MorphInjectorProperties" minOccurs="0" nillable="true" />
							<xs:element name="fullTfHediffProps" type="MorphHediffProperties" minOccurs="0" nillable="true" />
							<xs:element name="partialTfHediffProps" type="MorphHediffProperties" minOccurs="0" nillable="true" />
						</xs:all>
						<xs:attribute name="ParentName" type="xs:string" use="optional" />
						<xs:attribute name="Name" type="xs:string" use="optional" />
						<xs:attribute name="Abstract" type="xs:boolean" use="optional" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="StatModifiersList">
		<xs:sequence>
			<xs:element name="li" type="StatModifier" />
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="HybridThoughtSettings">
		<xs:sequence>
			<xs:element name="replacerList" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="li" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="original" type="xs:string" />
									<xs:element name="replacer" type="xs:string" />
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="ateAnimalThought" minOccurs="0" maxOccurs="1" type="AteThought"></xs:element>
			<xs:element name="butcheredAnimalThought" type="ButcherThought" minOccurs="0" maxOccurs="1" />
			<xs:element name="suppressHumanlikeCannibalThoughts" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="canEatRaw" type="xs:boolean" minOccurs="0" maxOccurs="1" />
			<xs:element name="thoughtsBlackList" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="li" type="xs:string" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="ateThoughtsSpecifics" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="li" type="AteThought" minOccurs="1" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="butcherThoughtsSpecifics" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="li" maxOccurs="unbounded" type="ButcherThought" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="AteThought">
		<xs:sequence>
			<xs:element name="thought" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="thoughtCannibal" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="ingredientThought" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="ingredientThoughtCannibal" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="raceList" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="li" type="xs:string" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="ButcherThought">
		<xs:sequence>
			<xs:element name="thought" type="xs:string" />
			<xs:element name="knowThought" type="xs:string" />
			<xs:element name="raceList" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="li" type="xs:string" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="TransformationSettings">
		<xs:sequence>
			<xs:element name="transformationTale" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="transformationMessageID" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="messageDef" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="transformationMemory" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="revertedMemory" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="revertedMemoryFurry" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="revertedMemoryBP" type="xs:string" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="TraitSettings">
		<xs:sequence>
			<xs:element name="forcedTraits" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="li" minOccurs="1" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="chance" type="xs:float" minOccurs="0" maxOccurs="1" />
									<xs:element name="commonalityMale" type="xs:float" minOccurs="0" maxOccurs="1" />
									<xs:element name="commonalityFemale" type="xs:float" minOccurs="0" maxOccurs="1" />
									<xs:element name="defName" type="xs:string" maxOccurs="1" minOccurs="1" />
									<xs:element name="degree" type="xs:int" maxOccurs="1" minOccurs="0" />
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="AddedAspect">
		<xs:sequence>
			<xs:element name="def" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="keepOnReversion" type="xs:boolean" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="StageAlert">
		<xs:all>
			<xs:element name="letterLabelText" type="xs:string" minOccurs="0" />
			<xs:element name="letterContentText" type="xs:string" minOccurs="0" />
			<xs:element name="letterDef" type="xs:string" minOccurs="0" />
		</xs:all>
	</xs:complexType>

	<xs:complexType name="TFMiscSettings">
		<xs:all>
			<xs:element name="tfTale" type="xs:string" minOccurs="0" />
			<xs:element name="warningLabelOverride" type="xs:string" minOccurs="0" />
			<xs:element name="warningContentOverride" type="xs:string" minOccurs="0" />
			<xs:element name="warningLetterDef" type="xs:string" minOccurs="0" />
			<xs:element name="displayWarning" type="xs:boolean" minOccurs="0" />
			<xs:element name="forcedSapience" type="xs:float" minOccurs="0" />
		</xs:all>
	</xs:complexType>

	<xs:complexType name="MorphHediffProperties">
		<xs:all>
			<xs:element name="label" type="xs:string" minOccurs="0" />
			<xs:element name="description" type="xs:string" minOccurs="0" />
			<xs:element name="labelColor" type="Color" minOccurs="0" />
			<xs:element name="MutagenDef" type="xs:string" minOccurs="0" />
			<xs:element name="tfAlert" type="StageAlert" minOccurs="0" />
			<xs:element name="removeNonMorphPartChance" type="xs:float" minOccurs="0" />
			<xs:element name="tfSettings" type="TFMiscSettings" minOccurs="0" />
			<xs:element name="hungerRateFactor" type="xs:float" minOccurs="0" />
			<xs:element name="capMods" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:any processContents="lax" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>

			<xs:element name="aspectGivers" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="li" minOccurs="1" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:any processContents="lax" maxOccurs="unbounded" />
								</xs:sequence>
								<xs:attribute name="Class" use="required" type="xs:string" />
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:all>
	</xs:complexType>

	<xs:complexType name="MorphInjectorProperties">
		<xs:all>
			<xs:element name="label" type="xs:string" minOccurs="0" />
			<xs:element name="statBases" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:any processContents="lax" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="workAmount" type="xs:positiveInteger" minOccurs="0" />
			<xs:element name="techLevel" type="TechLevel" minOccurs="0" />
			<xs:element name="traderTags" type="ListOfStrings" minOccurs="0" />
			<xs:element name="description" type="xs:string" minOccurs="0" />
			<xs:element name="useDefaultTags" type="xs:boolean" minOccurs="0" />
			<xs:element name="costList" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:any processContents="lax" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="slurryCost" type="xs:positiveInteger" minOccurs="0" />
			<xs:element name="neutroamineCost" type="xs:positiveInteger" minOccurs="0" />
			<xs:element name="mutaniteCost" type="xs:positiveInteger" minOccurs="0" />
			<xs:element name="outcomeDoers" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="li" minOccurs="1" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:any processContents="lax" maxOccurs="unbounded" />
								</xs:sequence>
								<xs:attribute name="Class" use="required" type="xs:string" />
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>

			<xs:element name="graphicData" type="GraphicData" minOccurs="0" />

			<xs:element name="recipeMaker" type="RecipeMaker" minOccurs="0" />
		</xs:all>
	</xs:complexType>
</xs:schema>

=== Tachyonite/Pawnmorpher/1.1/Defs/Morphs/Elephant/Elephant_MorphDef.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../Schemas/MorphDef.xsd">
	<Pawnmorph.MorphDef ParentName="SensitiveFoodMorph">
		<defName>ElephantMorph</defName>
		<label>elephantmorph</label>
		<description>A large human that has been exposed to large amounts of elephant specific mutagens. They usually have much in common with their feral counterparts like thick hide and large tusks, making them very dangerous in combat.</description>
		<race>Elephant</race>
		<classification>ThickHide</classification>
		<categories>
			<li>Powerful</li>
		</categories>
		<fullTransformation>PawnmorphElephantTF</fullTransformation>
		<partialTransformation>PawnmorphElephantTFPartial</partialTransformation>
		<raceSettings>
			<graphicsSettings>
				<skinColorOverride>(130,126,119)</skinColorOverride>
			</graphicsSettings>
		</raceSettings>
		<transformSettings>
			<transformationMemory>ElephantTransformationMemory</transformationMemory>
			<revertedMemory>ElephantRevertedMemory</revertedMemory>
		</transformSettings>
	</Pawnmorph.MorphDef>
</Defs>

=== Tachyonite/Pawnmorpher/1.3/Defs/Morphs/Fox/Arctic Fox/ArcticFox_MorphDef.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../Schemas/MorphDef.xsd">
	<Pawnmorph.MorphDef ParentName="FoxMorphBase">
		<defName>ArcticFoxMorph</defName>
		<label>arcticfoxmorph</label>
		<race>Fox_Arctic</race>
		<categories>
			<li>Cold</li>
			<li>Combat</li>
			<li>Social</li>
			<li>Canid</li>
		</categories>
		<injectorProperties></injectorProperties>
		<partialTransformation>PawnmorphArcticFoxTFPartial</partialTransformation>
		<fullTransformation>PawnmorphArcticFoxTF</fullTransformation>
		<raceSettings>
			<graphicsSettings>
				<skinColorOverride>(220,220,220)</skinColorOverride>
			</graphicsSettings>
		</raceSettings>
	</Pawnmorph.MorphDef>
</Defs>

=== Tachyonite/Pawnmorpher/1.1/Defs/Morphs/Fox/Red Fox/RedFox_MorphDef.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../Schemas/MorphDef.xsd">
	<Pawnmorph.MorphDef ParentName="FoxMorphBase">
		<defName>FoxMorph</defName>
		<label>foxmorph</label>
		<race>Fox_Red</race>
		<categories>
			<li>Temperate</li>
			<li>Combat</li>
			<li>Social</li>
			<li>Canid</li>
		</categories>
		<partialTransformation>PawnmorphFoxTFPartial</partialTransformation>
		<fullTransformation>PawnmorphFoxTF</fullTransformation>
		<raceSettings>
			<graphicsSettings>
				<skinColorOverride>(178,99,33)</skinColorOverride>
			</graphicsSettings>
		</raceSettings>
	</Pawnmorph.MorphDef>
</Defs>

=== Tachyonite/Pawnmorpher/1.6/Defs/MorphsAndMutationDefs/Animal/PawFooted/Ursine/Grizzly Bear/GrizzlyBear_MorphDef.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../../Schemas/MorphDef.xsd">
	<Pawnmorph.MorphDef ParentName="UrsineMorph">
		<defName>BearMorph</defName>
		<label>grizzlybearmorph</label>
		<race>Bear_Grizzly</race>
		<fullTransformation>PawnmorphBearTF</fullTransformation>
		<partialTransformation>PawnmorphBearTFPartial</partialTransformation>
		<categories>
			<li>Cold</li>
			<li>Temperate</li>
		</categories>
		<raceSettings>
			<graphicsSettings>
				<skinColorOverride>(112,82,65)</skinColorOverride>
			</graphicsSettings>
		</raceSettings>
	</Pawnmorph.MorphDef>
</Defs>

=== Tachyonite/Pawnmorpher/1.6/Defs/MorphsAndMutationDefs/Animal/PawFooted/Carnivora/Canid/Familiaris/LabradorRetriever/LabradorRetriever_MorphDef.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../../../../Schemas/MorphDef.xsd">
	<Pawnmorph.MorphDef ParentName="FamiliarisMorph">
		<defName>LabradorRetrieverMorph</defName>
		<label>labmorph</label>
		<race>LabradorRetriever</race>
		<fullTransformation>PawnmorphLabradorRetrieverTF</fullTransformation>
		<partialTransformation>PawnmorphLabradorRetrieverTFPartial</partialTransformation>
		<raceSettings>
			<graphicsSettings>
				<skinColorOverride>(220,198,160)</skinColorOverride>
			</graphicsSettings>
		</raceSettings>
	</Pawnmorph.MorphDef>
</Defs>

=== Tachyonite/Pawnmorpher/1.6/Defs/MorphsAndMutationDefs/Animal/Ungulate/EvenToedUngulate/Cervid/Boomalope/Boomalope_MorphDef.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../Schemas/MorphDef.xsd">
	<Pawnmorph.MorphDef ParentName="CervidMorph">
		<defName>BoomalopeMorph</defName>
		<label>boomamorph</label>
		<description>A humanoid sharing many characteristics with boomalopes, due to heavy mutagen exposure. They usually have thick hide, and an urge to seek out chemfuel.</description>
		<race>Boomalope</race>
		<categories>
			<li>Arid</li>
			<li>Temperate</li>
			<li>Tropical</li>
			<li>Production</li>
		</categories>
		<fullTransformation>PawnmorphBoomalopeTF</fullTransformation>
		<partialTransformation>PawnmorphBoomalopeTFPartial</partialTransformation>
		<raceSettings>
			<graphicsSettings>
				<skinColorOverride>(176,150,106)</skinColorOverride>
			</graphicsSettings>
		</raceSettings>
		<transformSettings>
			<transformationMemory>BoomalopeTransformationMemory</transformationMemory>
			<revertedMemory>BoomalopeRevertedMemory</revertedMemory>
		</transformSettings>
	</Pawnmorph.MorphDef>
</Defs>

=== Tachyonite/Pawnmorpher/1.4/Defs/MorphsAndMutationDefs/Animal/Ungulate/EvenToedUngulate/Suid/Pig/Pig_MorphDef.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../Schemas/MorphDef.xsd">
	<Pawnmorph.MorphDef ParentName="SuidMorph">
		<defName>PigMorph</defName>
		<label>pigmorph</label>
		<description>A humanoid race resulting from a human being exposed to pig specific mutagens. They are often fond of looking through dirt and grass to find edible mushrooms.</description>
		<race>Pig</race>
		<categories>
			<li>Domestic</li>
		</categories>
		<fullTransformation>PawnmorphPigTF</fullTransformation>
		<partialTransformation>PawnmorphPigTFPartial</partialTransformation>
		<raceSettings>
			<graphicsSettings>
				<skinColorOverride>(211,190,174)</skinColorOverride>
			</graphicsSettings>
		</raceSettings>
		<transformSettings>
			<transformationMemory>PigTransformationMemory</transformationMemory>
			<revertedMemory>PigRevertedMemory</revertedMemory>
		</transformSettings>
	</Pawnmorph.MorphDef>
</Defs>

=== Tachyonite/Pawnmorpher/1.4/Defs/MorphsAndMutationDefs/Animal/PawFooted/Ursine/Ursine_MorphDef.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../Schemas/MorphDef.xsd">
	<Pawnmorph.MorphDef Abstract="true" ParentName="PawFootedMorph" Name="UrsineMorph">
		<description>Bearmorphs are combat experts. Usually equipped with large claws, paws and maws, they are devastatingly dangerous up close. But they have a tender heart, and a soft spot for plush toys of the ursine variety.</description>
		<classification>Ursine</classification>
		<categories>
			<li>Combat</li>
		</categories>
		<transformSettings>
			<transformationMemory>BearTransformationMemory</transformationMemory>
			<revertedMemory>BearRevertedMemory</revertedMemory>
		</transformSettings>
	</Pawnmorph.MorphDef>
</Defs>
