=== Tachyonite/Pawnmorpher/Schemas/MutationDef.xsd
<?xml version="1.0" encoding="utf-8" ?>

<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:include schemaLocation="include/SimpleTypes.xsd" />
    <xs:include schemaLocation="include/CommonComplex.xsd" />
    <xs:element name="Defs">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Pawnmorph.Hediffs.MutationDef" type="MutationDef" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="MutationDef">
        <xs:all>
            <xs:element name="defName" type="xs:string" minOccurs="0" />
            <xs:element name="label" type="xs:string" minOccurs="0" />
            <xs:element name="description" type="xs:string" minOccurs="0" />
            <xs:element name="maxSeverity" type="xs:float" minOccurs="0" />
            <xs:element name="initialSeverity" type="xs:float" minOccurs="0" />
            <xs:element name="hediffClass" type="xs:string" minOccurs="0" />
            <xs:element name="defaultAddChance" type="xs:float" minOccurs="0"/>
            <xs:element name="defaultBlocks" type="xs:boolean" minOccurs="0"/>
            <xs:element name="isBad" type="xs:boolean" minOccurs="0"/>
            <xs:element name="value" type="xs:int" minOccurs="0" />
            <xs:element name="blockSites" type="ListOfStrings" minOccurs="0" />
            <xs:element name="graphics" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:any processContents="lax" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="blockEntries" minOccurs="0" >
                <xs:complexType>
                    <xs:sequence>
                         <xs:element name="li" minOccurs="1"  type="BlockEntry" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="comps" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="li" type="xs:anyType"  maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="stages" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="li" type="HediffStage" maxOccurs="unbounded" />
                    </xs:sequence>
                    <xs:attribute name="Inherit" type="xs:boolean" use="optional" />
                </xs:complexType>
            </xs:element>
            <xs:element name="stagePatches" minOccurs="0">
				<xs:complexType>
				    <xs:sequence>
						<xs:element name="li" minOccurs="1" maxOccurs="unbounded">
							<xs:complexType>
								<xs:all>
								    <xs:element name="stageKey" type="xs:string" minOccurs="0" />
								    <xs:element name="values" type="HediffStage" minOccurs="0" />
								</xs:all>
								<xs:attribute name="function" type="xs:string" use="optional" />
							</xs:complexType>
						</xs:element>
				    </xs:sequence>
				</xs:complexType>
            </xs:element>
            <xs:element name="spawnThingOnRemoved" type="xs:string" minOccurs="0"/>
            <xs:element name="parts" minOccurs="0" type="ListOfStrings" />
            <xs:element name="categories" minOccurs="0" type="ListOfStrings" />
            <xs:element name="customGenomeDescription" minOccurs="0" type="xs:string" />
            <xs:element name="mutationTale" minOccurs="0" type="xs:string" />
            <xs:element name="isTaggable" minOccurs="0" type="xs:boolean" />
            <xs:element name="classInfluence" minOccurs="0" type="xs:string" />
            <xs:element name="classInfluences" minOccurs="0" type="ListOfStrings" />
            <xs:element name="mutationMemory" minOccurs="0" type="xs:string" />
            <xs:element name="memoryIgnoresLimit" minOccurs="0" type="xs:boolean" />
            <xs:element name="mutationLogRulePack" minOccurs="0" type="xs:string" />
            <xs:element name="countToAffect" minOccurs="0" type="xs:int" />
            <xs:element name="modExtensions" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="li" type="xs:anyType" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:all>
        <xs:attribute name="ParentName" type="xs:string" use="optional" />
        <xs:attribute name="Abstract" type="xs:boolean" use="optional" />
        <xs:attribute name="Name" type="xs:string" use="optional" />
    </xs:complexType>
    <xs:complexType name="HediffStage">
        <xs:all>
		    <xs:element name="key" minOccurs="0" type="xs:string" />
            <xs:element name="minSeverity" minOccurs="0" type="xs:float" />
            <xs:element name="label" minOccurs="0" type="xs:string" />
            <xs:element name="labelOverride" minOccurs="0" type="xs:string" />
            <xs:element name="description" minOccurs="0" type="xs:string" />
            <xs:element name="painOffset" type="xs:float" minOccurs="0" />
            <xs:element name="healthOffset" type="xs:float" minOccurs="0" />
			<xs:element name="globalHealthMultiplier" type="xs:float" minOccurs="0" />
            <xs:element name="graphics" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:any processContents="lax" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="skipAspects" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="li" minOccurs="1" maxOccurs="unbounded">
                            <xs:complexType>
                                <xs:all>
                                    <xs:element name="aspect" minOccurs="1" maxOccurs="1" type="xs:string" />
                                    <xs:element name="stage" minOccurs="0" maxOccurs="1" type="xs:positiveInteger" />
                                </xs:all>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="partEfficiencyOffset" minOccurs="0" type="xs:float" />
            <xs:element name="hungerRateFactor" minOccurs="0" type="xs:float" />
            <xs:element name="stopChance" minOccurs="0" type="xs:float" />
            <xs:element name="memory" minOccurs="0" type="xs:string" />
            <xs:element name="capMods" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:any processContents="lax" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="hediffGivers" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="li" type="xs:anyType" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="statOffsets" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:any processContents="lax" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="statFactors" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:any processContents="lax" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>

            <xs:element name="aspectGivers" minOccurs="0">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="li" type="xs:anyType" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:all>
        <xs:attribute name="Class" type="CustomHediffStages" use="optional" />
    </xs:complexType>

    <xs:simpleType name="CustomHediffStages">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Pawnmorph.Hediffs.DescriptiveStage" />
            <xs:enumeration value="Pawnmorph.Hediffs.MutationStage" />
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="BlockEntry">
        <xs:all>
            <xs:element name="mutation" type="xs:string" minOccurs="1" />
            <xs:element name="blockOnAnyPart" type="xs:boolean" minOccurs="0" />
        </xs:all>
    </xs:complexType>
</xs:schema>

=== Tachyonite/Pawnmorpher/1.4/Defs/MorphsAndMutationDefs/Animal/Ungulate/OddToedUngulate/Equine/Equine_Parts.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../../Schemas/MutationDef.xsd">
	<Pawnmorph.Hediffs.MutationDef Name ="EquineJawPart" ParentName="OddToedUngulateJawPart" Abstract="true">
		<mutationMemory>EtherEquineMuzzle</mutationMemory>
		<stagePatches>
			<li function="modify">
				<stageKey>adapting</stageKey>
				<values>
					<description>[PAWN_nameDef] has grown a sizable snout with wide nostrils and a small set of squared off teeth, giving [PAWN_objective] quite a long face. Don't ask why. The strange shape makes speaking very difficult.</description>
				</values>
			</li>
			<li function="modify">
				<stageKey>adapted</stageKey>
				<values>
					<description>[PAWN_nameDef] has grown a sizable snout with wide nostrils and a small set of squared off teeth, giving [PAWN_objective] quite a long face. Don't ask why. Adapting to it has made speaking less frustrating.</description>
				</values>
			</li>
			<li function="modify">
				<stageKey>paragon</stageKey>
				<values>
					<description>[PAWN_nameDef] has grown a sizable snout with wide nostrils and a small set of squared off teeth, giving [PAWN_objective] quite a long face. Don't ask why. With further adaptation, [PAWN_nameDef] has learned to speak normally.</description>
				</values>
			</li>
		</stagePatches>
	</Pawnmorph.Hediffs.MutationDef>

	<Pawnmorph.Hediffs.MutationDef Name ="EquineEarPart" ParentName="OddToedUngulateEarPart" Abstract="true">
		<mutationMemory>EtherEquineEar</mutationMemory>
		<stagePatches>
			<li function="modify">
				<stageKey>growing</stageKey>
				<values>
					<capMods>
						<li>
							<capacity>Hearing</capacity>
							<offset>+0.05</offset>
						</li>
					</capMods>
				</values>
			</li>
			<li function="modify">
				<stageKey>grown</stageKey>
				<values>
					<capMods>
						<li>
							<capacity>Hearing</capacity>
							<offset>+0.1</offset>
						</li>
					</capMods>
				</values>
			</li>
		</stagePatches>
	</Pawnmorph.Hediffs.MutationDef>

	<Pawnmorph.Hediffs.MutationDef Name ="EquineTailPart" ParentName="OddToedUngulateTailPart" Abstract="true">
		<mutationMemory>EtherEquineTail</mutationMemory>
	</Pawnmorph.Hediffs.MutationDef>

</Defs>

=== Tachyonite/Pawnmorpher/1.2/Defs/Morphs/Fox/Arctic Fox/ArcticFox_Parts.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../Schemas/MutationDef.xsd">
	<Pawnmorph.Hediffs.MutationDef ParentName="FoxJawBase">
		<defName>EtherArcticFoxMuzzle</defName>
		<classInfluence>ArcticFoxMorph</classInfluence>
	</Pawnmorph.Hediffs.MutationDef>
	<Pawnmorph.Hediffs.MutationDef ParentName="FoxEarBase">
		<defName>EtherArcticFoxEar</defName>
		<classInfluence>ArcticFoxMorph</classInfluence>
	</Pawnmorph.Hediffs.MutationDef>
	<Pawnmorph.Hediffs.MutationDef ParentName="FoxTailBase">
		<defName>EtherArcticFluffyTail</defName>
		<classInfluence>ArcticFoxMorph</classInfluence>
	</Pawnmorph.Hediffs.MutationDef>
	<Pawnmorph.Hediffs.MutationDef ParentName="PM_ArcticFurBase">
		<defName>EtherArcticFoxFur</defName>
		<classInfluence>ArcticFoxMorph</classInfluence>
	</Pawnmorph.Hediffs.MutationDef>
</Defs>

=== Tachyonite/Pawnmorpher/1.6/Defs/MorphsAndMutationDefs/Animal/Ungulate/EvenToedUngulate/Caprid/Ibex/Ibex_Parts.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../../../Schemas/MutationDef.xsd">
	<Pawnmorph.Hediffs.MutationDef ParentName="CapridJawPart">
		<classInfluence>IbexMorph</classInfluence>
		<defName>EtherIbexSnout</defName>
		<label>ibex snout</label>
		<graphics>
			<Muzzle>Parts/Ibex/Ibex_Muzzle</Muzzle>
		</graphics>
	</Pawnmorph.Hediffs.MutationDef>
	
	<Pawnmorph.Hediffs.MutationDef ParentName="CapridEarPart">
		<classInfluence>IbexMorph</classInfluence>
		<defName>EtherIbexEar</defName>
		<label>ibex ear</label>
		<graphics>
			<LeftEar>Parts/Ibex/Ibex_Ear_Left</LeftEar>
			<LeftEarBehind>Parts/Ibex/Ibex_Ear_Left_Behind</LeftEarBehind>
			<RightEar>Parts/Ibex/Ibex_Ear_Right</RightEar>
			<RightEarBehindHead>Parts/Ibex/Ibex_Ear_Right_Behind</RightEarBehindHead>
		</graphics>
		<stagePatches>
			<li function="modify">
				<stageKey>grown</stageKey>
				<values>
					<description>A fluffy, caprine ear sits at the side of [PAWN_nameDef]'s head, like that of an ibex.</description>
				</values>
			</li>
		</stagePatches>
	</Pawnmorph.Hediffs.MutationDef>
	
	<Pawnmorph.Hediffs.MutationDef ParentName="CapridTailPart">
		<classInfluence>IbexMorph</classInfluence>
		<defName>EtherIbexTail</defName>
		<label>ibex tail</label>
		<graphics>
			<Tail>Parts/Ibex/Ibex_Tail</Tail>
		</graphics>
		<stagePatches>
			<li function="modify">
				<stageKey>grown</stageKey>
				<values>
					<description>A tail like that of an Ibex goat. It's very wooly but short and not very useful.</description>
				</values>
			</li>
		</stagePatches>
	</Pawnmorph.Hediffs.MutationDef>
	
	
	<Pawnmorph.Hediffs.MutationDef ParentName="CapridHornPart">
		<defName>EtherIbexHorns</defName>
		<classInfluence>IbexMorph</classInfluence>
		<label>ibex horns</label>
		<description>The curved horns of an ibex. They start small, but will eventually grow to full size. Horn growth does not require the constant work of mutagenic mechanites.</description>
		<!-- <mutationTale>TODO</mutationTale>
		<mutationMemory>TODO</mutationMemory> -->
		<stagePatches>
			<li function="modify">
				<stageKey>nubs</stageKey>
				<values>
					<graphics>
						<Horns>Parts/Ibex/Ibex_Horns_A</Horns>
					</graphics>
				</values>
			</li>
			<li function="modify">
				<stageKey>short</stageKey>
				<values>
					<description>Long, curved horns grows from [PAWN_nameDef]'s head. They are already larger than even most but still have a little more growing to do.</description>
					<graphics>
						<Horns>Parts/Ibex/Ibex_Horns_B</Horns>
					</graphics>
				</values>
			</li>
			<li function="modify">
				<stageKey>horns</stageKey>
				<values>
					<description>Incredibly long Ibex horns crowns [PAWN_nameDef]'s head, moving through doors is difficult but they add great heft to any headbutt.</description>
					<graphics>
						<Horns>Parts/Ibex/Ibex_Horns_C</Horns>
					</graphics>
				</values>
			</li>
		</stagePatches>
	</Pawnmorph.Hediffs.MutationDef>
</Defs>

=== Tachyonite/Pawnmorpher/1.3/Defs/MorphsAndMutationDefs/Animal/PawFooted/Carnivora/Feline/Felis/Felis_Parts.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../../../Schemas/MutationDef.xsd">
	<Pawnmorph.Hediffs.MutationDef Name ="FelisJawPart" ParentName="FelineJawPart" Abstract="true">
		<mutationMemory>EtherCatMuzzle</mutationMemory>
		<stagePatches>
			<li function="modify">
				<stageKey>adapting</stageKey>
				<values>
					<description>[PAWN_nameDef]'s face has pressed out into a cat shape. They may hiss and meow more than talk. The strange shape makes speaking very difficult.</description>
				</values>
			</li>
			<li function="modify">
				<stageKey>adapted</stageKey>
				<values>
					<description>[PAWN_nameDef]'s face has pressed out into a cat shape. They may hiss and meow more than talk. Adapting to it has made speaking less frustrating.</description>
				</values>
			</li>
			<li function="modify">
				<stageKey>paragon</stageKey>
				<values>
					<description>[PAWN_nameDef]'s face has pressed out into a cat shape. They may hiss and meow more than talk. With further adaptation, [PAWN_nameDef] has learned to speak normally.</description>
				</values>
			</li>
		</stagePatches>
	</Pawnmorph.Hediffs.MutationDef>

	<Pawnmorph.Hediffs.MutationDef Name ="FelisEarPart" ParentName="FelineEarPart" Abstract="true">
		<stagePatches>
			<li function="modify">
				<stageKey>grown</stageKey>
				<values>
					<description>a triangular, fuzzy ear graces [PAWN_nameDef]'s head. It coils back when [PAWN_pronoun] is getting ready to pounce.</description>
				</values>
			</li>
		</stagePatches>
	</Pawnmorph.Hediffs.MutationDef>

	<Pawnmorph.Hediffs.MutationDef Name ="FelisTailPart" ParentName="FelineTailPart" Abstract="true">
		<stagePatches>
			<li function="modify">
				<stageKey>growing</stageKey>
				<values>
					<capMods>
						<li>
							<capacity>Moving</capacity>
							<offset>+0.025</offset>
						</li>
					</capMods>
					<statOffsets>
						<HuntingStealth>+0.1</HuntingStealth>
						<PawnBeauty>+0.01</PawnBeauty>
					</statOffsets>
				</values>
			</li>
			<li function="modify">
				<stageKey>grown</stageKey>
				<values>
					<description>A long, cat-like tail. It flicks back and forth whenever [PAWN_nameDef] is displeased with something.</description>
					<capMods>
						<li>
							<capacity>Moving</capacity>
							<offset>+0.05</offset>
						</li>
					</capMods>
					<statOffsets>
						<HuntingStealth>+0.2</HuntingStealth>
						<PawnBeauty>+0.01</PawnBeauty>
					</statOffsets>
				</values>
			</li>
		</stagePatches>
	</Pawnmorph.Hediffs.MutationDef>

</Defs>

=== Tachyonite/Pawnmorpher/1.4/Defs/MorphsAndMutationDefs/Animal/PawFooted/Carnivora/Feline/BigFelis/Lynx/Lynx_Parts.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../../../../Schemas/MutationDef.xsd">
	<Pawnmorph.Hediffs.MutationDef ParentName="BigFelisJawPart">
		<classInfluence>LynxMorph</classInfluence>
		<defName>EtherLynxJaw</defName>
		<label>lynx snout</label>
		<graphics>
			<Muzzle>Parts/Lynx/Lynx_Muzzle</Muzzle>
		</graphics>
	</Pawnmorph.Hediffs.MutationDef>

	<Pawnmorph.Hediffs.MutationDef ParentName="BigFelisEarPart">
		<classInfluence>LynxMorph</classInfluence>
		<defName>EtherLynxEar</defName>
		<label>lynx ear</label>
		<graphics>
			<LeftEar>Parts/Lynx/Lynx_Ear_Left</LeftEar>
			<LeftEarBehind>Parts/Lynx/Lynx_Ear_Left_Behind</LeftEarBehind>
			<RightEar>Parts/Lynx/Lynx_Ear_Right</RightEar>
			<RightEarBehindHead>Parts/Lynx/Lynx_Ear_Right_Behind</RightEarBehindHead>
		</graphics>
		<stagePatches>
			<li function="modify">
				<stageKey>grown</stageKey>
				<values>
					<description>With a pointed tip and fluff of fur at the end, this ear has grown into what looks like a lynx's style of auditory apparatus.</description>
				</values>
			</li>
		</stagePatches>
	</Pawnmorph.Hediffs.MutationDef>

	<Pawnmorph.Hediffs.MutationDef ParentName="BigFelisTailPart">
		<classInfluence>LynxMorph</classInfluence>
		<defName>EtherLynxTail</defName>
		<label>lynx tail</label>
		<graphics>
			<Tail>Parts/Lynx/Lynx_Tail</Tail>
		</graphics>
		<stagePatches>
			<li function="modify">
				<stageKey>grown</stageKey>
				<values>
					<description>Unlike most felines, the tail of a lynx is short and stubby. [PAWN_nameDef] has one of them now.</description>
				</values>
			</li>
		</stagePatches>
	</Pawnmorph.Hediffs.MutationDef>
</Defs>
