=== Tachyonite/Pawnmorpher/Schemas/RulePackDef.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Defs">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="RulePackDef" minOccurs="1" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="defName" type="xs:string" minOccurs="0" maxOccurs="1"/>
                            <xs:element name="rulePack" minOccurs="0" maxOccurs="1">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="rulesStrings" minOccurs="1" maxOccurs="1">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="li" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
                                            </xs:sequence>
                                        </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="ParentName" type="AbstractRulePacks" use="optional"/>
                        <xs:attribute name="Abstract" type="xs:boolean" use="optional"/>
                        <xs:attribute name="Name" type="xs:string" use="optional"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>



    <xs:simpleType name="AbstractRulePacks">
        <xs:restriction base="xs:string">
            <xs:enumeration value="CustomMutationRulePackBase"/>
            <xs:enumeration value="SimpleMutationRulePackBase"/>
            <xs:enumeration value="CoveringMutationLogPackBase"/>
            <xs:enumeration value="AddedPartLogBase" />
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== Tachyonite/Pawnmorpher/1.1/Defs/RulePacks/FormerHumans/FH_RecruitAttempts.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../Schemas/RulePackDef.xsd">
    <RulePackDef>
        <defName>SapientAnimalRecruitSuccess</defName>
        <rulePack>
            <rulesStrings>
                <li>sent->[RECIPIENT_nameDef] has accepted and joined [INITIATOR_nameDef]'s community.</li>
            </rulesStrings>
        </rulePack>
    </RulePackDef>

    <RulePackDef>
        <defName>MostlySapientAnimalRecruitSuccess</defName>
        <rulePack>
            <rulesStrings>
                <li>sent->[RECIPIENT_nameDef] has accepted and joined [INITIATOR_nameDef]'s community.</li>
            </rulesStrings>
        </rulePack>
    </RulePackDef>


    <!-- Failure -->

    <RulePackDef>
        <defName>SapientAnimalRecruitRejected</defName>
        <rulePack>
            <rulesStrings>
                <li>sent->[RECIPIENT_nameDef] refused.</li>
                <li>sent->[RECIPIENT_nameDef] told [INITIATOR_objective] to shove it.</li>
                <li>sent->[RECIPIENT_nameDef] told [INITIATOR_objective] to get lost.</li>
                <li>sent->[RECIPIENT_nameDef] yelled at [INITIATOR_objective].</li>
                <li>sent->[RECIPIENT_nameDef] made a rude gesture at [INITIATOR_objective].</li>
                <li>sent->[RECIPIENT_nameDef] rolled [RECIPIENT_possessive] eyes at [INITIATOR_objective].</li>
            </rulesStrings>
        </rulePack>
    </RulePackDef>
    <RulePackDef>
        <defName>MostlySapientAnimalRecruitRejected</defName>
        <rulePack>
            <rulesStrings>
                <li>sent->[RECIPIENT_nameDef] refused.</li>
                <li>sent->[RECIPIENT_nameDef] made a rude gesture at [INITIATOR_objective].</li>
                <li>sent->[RECIPIENT_nameDef] rolled [RECIPIENT_possessive] eyes at [INITIATOR_objective].</li>
            </rulesStrings>
        </rulePack>
    </RulePackDef>
</Defs>
