=== Tachyonite/Pawnmorpher/Schemas/ThoughtDef.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="DefExtensions/FilterExtensions.xsd" />
	<xs:element name="Defs">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ThoughtDef" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:all>
							<xs:element name="defName" type="xs:string" minOccurs="0" maxOccurs="1" />
							<xs:element name="thoughtClass" type="xs:string" minOccurs="0" maxOccurs="1" />
							<xs:element name="workerClass" type="xs:string" minOccurs="0" maxOccurs="1" />
							<xs:element name="durationDays" type="xs:float" minOccurs="0" maxOccurs="1" />
							<xs:element name="morph" type="xs:string" maxOccurs="1" minOccurs="0" />
							<xs:element name="aspect" type="xs:string" maxOccurs="1" minOccurs="0" />
							<xs:element name="hediff" type="xs:string" minOccurs="0" maxOccurs="1" />
							<xs:element name="showBubble" type="xs:boolean" minOccurs="0"/>
							<xs:element name="icon" type="xs:string" minOccurs="0"/>
							<xs:element name="validWhileDespawned" type="xs:boolean" minOccurs="0"/>
							<xs:element name="stackLimit" type="xs:positiveInteger" minOccurs="0" />
							<xs:element name="requiredTraits" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="li" type="xs:string" minOccurs="1" maxOccurs="unbounded" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="nullifyingTraits" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="li" minOccurs="1" maxOccurs="unbounded" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="stages" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="li" type="ThoughtStage" minOccurs="1" maxOccurs="unbounded" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="modExtensions" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="li" type="xs:anyType" maxOccurs="unbounded" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:all>
						<xs:attribute name="ParentName" type="xs:string" use="optional" />
						<xs:attribute name="Abstract" type="xs:boolean" use="optional" />
						<xs:attribute name="Name" type="xs:string" use="optional" />
						<xs:attribute name="Class" type="xs:string" use="optional" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>


	<xs:simpleType name="ThoughtDefClasses">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Pawnmorph.Thoughts.Def_MorphThought" />
			<xs:enumeration value="Pawnmorph.Thoughts.Def_AspectThought" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="AbstractThoughts">
		<xs:restriction base="xs:string">
			<xs:enumeration value="OutlookMemoryBase" />
			<xs:enumeration value="GroupThoughtBase" />
			<xs:enumeration value="FH_NakedThought"/>
			<xs:enumeration value="FH_PersistentThought" />
			<xs:enumeration value="FH_NakedThougthNudist" />
			<xs:enumeration value="FH_MemoryBase"/>
			<xs:enumeration value="FH_FeralPillBase" />
			<xs:enumeration value="SapientAnimalBondedMasterBase" />
			<xs:enumeration value="SapientAnimalBondedNonMasterBase" />
			<xs:enumeration value="FormerHumanCannibalThoughtBase" />
			<xs:enumeration value="FormerHumanCannibalThoughtGoodBase" />
			<xs:enumeration value="AnimalisticPersistentThoughtBase" />
			<xs:enumeration value="DefaultReactionBase"/>
			<xs:enumeration value="SapientMemoryBase" />
			<xs:enumeration value="AnimalisticNakedThought" />
			<xs:enumeration value="AnimalisticNakedThougthNudist" />
			<xs:enumeration value="MergedPawnPersistentBase" />
			<xs:enumeration value="SleptThoughtBase" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="ThoughtStage">
		<xs:all>
			<xs:element name="label" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="labelSocial" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="description" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="visible" type="xs:boolean" default="true" minOccurs="0" maxOccurs="1" />
			<xs:element name="baseMoodEffect" type="xs:float" minOccurs="0" maxOccurs="1" />
		</xs:all>
		<xs:attribute name="IsNull" type="xs:boolean" use="optional" />
	</xs:complexType>
</xs:schema>

=== Tachyonite/Pawnmorpher/1.3/Defs/MorphsAndMutationDefs/Animal/PawFooted/Carnivora/Feline/Pantherine/Leopard/Snowleopard_Memories.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../../../../Schemas/ThoughtDef.xsd">

	<ThoughtDef ParentName="OutlookMemoryBase">
        <durationDays>1</durationDays>
        <defName>EtherSnowLeopardJaw</defName>
        <stages>
            <li>
                <label>Snowy face</label>
                <description>It's hard to talk without purring.</description>
                <visible>true</visible>
                <baseMoodEffect>-1</baseMoodEffect>
            </li>
            <li>
                <label>Snowy face</label>
                <description>Mrrow!</description>
                <visible>true</visible>
                <baseMoodEffect>2</baseMoodEffect>
            </li>
            <li>
                <label>Snowy face</label>
                <description>No! I don't want to purr!</description>
                <visible>true</visible>
                <baseMoodEffect>-3</baseMoodEffect>
            </li>
        </stages>
    </ThoughtDef>
	
    <ThoughtDef ParentName="OutlookMemoryBase">
        <durationDays>1</durationDays>
        <defName>EtherSnowLeopardEar</defName>
        <stages>
            <li>
                <label>Snowy ears</label>
                <description>As far as things go, these aren't too bad. They're kinda cute, actually.</description>
                <visible>true</visible>
                <baseMoodEffect>1</baseMoodEffect>
            </li>
            <li>
                <label>Snowy ears</label>
                <description>I can hear everything!</description>
                <visible>true</visible>
                <baseMoodEffect>2</baseMoodEffect>
            </li>
            <li>
                <label>Snowy ears</label>
                <description>I feel like an anime character...</description>
                <visible>true</visible>
                <baseMoodEffect>-2</baseMoodEffect>
            </li>
        </stages>
    </ThoughtDef>
	
    <ThoughtDef ParentName="OutlookMemoryBase">
        <durationDays>1</durationDays>
        <defName>EtherSnowLeopardTail</defName>
        <stages>
            <li>
                <label>Snowy tail</label>
                <description>Sure, it's fluffy and all, but it kind of gets in the way...</description>
                <visible>true</visible>
                <baseMoodEffect>-1</baseMoodEffect>
            </li>
            <li>
                <label>Snowy tail</label>
                <description>So big! So fluffy! I love it!</description>
                <visible>true</visible>
                <baseMoodEffect>1</baseMoodEffect>
            </li>
            <li>
                <label>Snowy tail</label>
                <description>God, this thing is always getting in my way...</description>
                <visible>true</visible>
                <baseMoodEffect>-2</baseMoodEffect>
            </li>
        </stages>
    </ThoughtDef>
	
</Defs>

=== Tachyonite/Pawnmorpher/1.6/Defs/MorphsAndMutationDefs/Animal/PawFooted/Rodent/Cerebral/Chinchilla/Chinchilla_Memories.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../../../Schemas/ThoughtDef.xsd">
    <ThoughtDef ParentName="OutlookMemoryBase">
		<defName>ChinchillaTransformationMemory</defName>
        <stages>
            <li>
                <label>changed</label>
                <description>Now everyone wants to pet me... Great...</description>
                <baseMoodEffect>-3</baseMoodEffect>
            </li>
            <li>
                <label>changed</label>
                <description>I look so adorable!</description>
                <baseMoodEffect>+3</baseMoodEffect>
            </li>
            <li>
                <label>changed</label>
                <description>Why do I feel so fragile ? And NO you canâ€™t pet me!</description>
                <baseMoodEffect>-5</baseMoodEffect>
            </li>
        </stages>
    </ThoughtDef>
	
    <ThoughtDef ParentName="OutlookMemoryBase">
		<defName>ChinchillaRevertedMemory</defName>
        <stages>
            <li>
                <label>reverted</label>
                <description>Finally, I had enough of being petted...</description>
                <baseMoodEffect>3</baseMoodEffect>
            </li>
            <li>
                <label>reverted</label>
                <description>I miss being petted...</description>
                <baseMoodEffect>-3</baseMoodEffect>
            </li>
            <li>
                <label>reverted</label>
                <description>It feels good not having glass bones!</description>
                <baseMoodEffect>10</baseMoodEffect>
            </li>
        </stages>
    </ThoughtDef>

    <ThoughtDef ParentName="OutlookMemoryBase">
        <durationDays>1</durationDays>
        <defName>EtherChinchillaJaw</defName>
        <stages>
            <li>
                <label>Tiny rodent face</label>
                <description>It's hard to eat when my mouth is so small!</description>
                <visible>true</visible>
                <baseMoodEffect>-1</baseMoodEffect>
            </li>
            <li>
                <label>Tiny rodent face</label>
                <description>My face is so tiny and cute!</description>
                <visible>true</visible>
                <baseMoodEffect>2</baseMoodEffect>
            </li>
            <li>
                <label>Tiny rodent face</label>
                <description>My face is so tiny!</description>
                <visible>true</visible>
                <baseMoodEffect>-3</baseMoodEffect>
            </li>
        </stages>
    </ThoughtDef>
	
    <ThoughtDef ParentName="OutlookMemoryBase">
        <durationDays>1</durationDays>
        <defName>EtherChinchillaEar</defName>
        <stages>
            <li>
                <label>Tiny rodent ears</label>
                <description>Huh... they're kinda cute, I guess.</description>
                <visible>True</visible>
                <baseMoodEffect>1</baseMoodEffect>
            </li>
            <li>
                <label>Tiny rodent ears</label>
                <description>These ears are adorable!</description>
                <visible>True</visible>
                <baseMoodEffect>2</baseMoodEffect>
            </li>
            <li>
                <label>Tiny rodent ears</label>
                <description>Does anyone have a hat I can hide these things under?</description>
                <visible>True</visible>
                <baseMoodEffect>-2</baseMoodEffect>
            </li>
        </stages>
    </ThoughtDef>
	
    <ThoughtDef ParentName="OutlookMemoryBase">
        <durationDays>1</durationDays>
        <defName>EtherChinchillaTail</defName>
        <stages>
            <li>
                <label>Tiny rodent tail</label>
                <description>Well, it *is* a little cool, I guess.</description>
                <visible>True</visible>
                <baseMoodEffect>1</baseMoodEffect>
            </li>
            <li>
                <label>Tiny rodent tail</label>
                <description>Awww, it's so tiny! I love it!</description>
                <visible>True</visible>
                <baseMoodEffect>2</baseMoodEffect>
            </li>
            <li>
                <label>Tiny rodent tail</label>
                <description>At least I can hide it...</description>
                <visible>True</visible>
                <baseMoodEffect>-2</baseMoodEffect>
            </li>
        </stages>
    </ThoughtDef>
</Defs>
