=== Tachyonite/Pawnmorpher/Schemas/ThoughtDef.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="DefExtensions/FilterExtensions.xsd" />
	<xs:element name="Defs">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ThoughtDef" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:all>
							<xs:element name="defName" type="xs:string" minOccurs="0" maxOccurs="1" />
							<xs:element name="thoughtClass" type="xs:string" minOccurs="0" maxOccurs="1" />
							<xs:element name="workerClass" type="xs:string" minOccurs="0" maxOccurs="1" />
							<xs:element name="durationDays" type="xs:float" minOccurs="0" maxOccurs="1" />
							<xs:element name="morph" type="xs:string" maxOccurs="1" minOccurs="0" />
							<xs:element name="aspect" type="xs:string" maxOccurs="1" minOccurs="0" />
							<xs:element name="hediff" type="xs:string" minOccurs="0" maxOccurs="1" />
							<xs:element name="showBubble" type="xs:boolean" minOccurs="0"/>
							<xs:element name="icon" type="xs:string" minOccurs="0"/>
							<xs:element name="validWhileDespawned" type="xs:boolean" minOccurs="0"/>
							<xs:element name="stackLimit" type="xs:positiveInteger" minOccurs="0" />
							<xs:element name="requiredTraits" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="li" type="xs:string" minOccurs="1" maxOccurs="unbounded" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="nullifyingTraits" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="li" minOccurs="1" maxOccurs="unbounded" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="stages" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="li" type="ThoughtStage" minOccurs="1" maxOccurs="unbounded" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="modExtensions" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="li" type="xs:anyType" maxOccurs="unbounded" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:all>
						<xs:attribute name="ParentName" type="xs:string" use="optional" />
						<xs:attribute name="Abstract" type="xs:boolean" use="optional" />
						<xs:attribute name="Name" type="xs:string" use="optional" />
						<xs:attribute name="Class" type="xs:string" use="optional" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>


	<xs:simpleType name="ThoughtDefClasses">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Pawnmorph.Thoughts.Def_MorphThought" />
			<xs:enumeration value="Pawnmorph.Thoughts.Def_AspectThought" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="AbstractThoughts">
		<xs:restriction base="xs:string">
			<xs:enumeration value="OutlookMemoryBase" />
			<xs:enumeration value="GroupThoughtBase" />
			<xs:enumeration value="FH_NakedThought"/>
			<xs:enumeration value="FH_PersistentThought" />
			<xs:enumeration value="FH_NakedThougthNudist" />
			<xs:enumeration value="FH_MemoryBase"/>
			<xs:enumeration value="FH_FeralPillBase" />
			<xs:enumeration value="SapientAnimalBondedMasterBase" />
			<xs:enumeration value="SapientAnimalBondedNonMasterBase" />
			<xs:enumeration value="FormerHumanCannibalThoughtBase" />
			<xs:enumeration value="FormerHumanCannibalThoughtGoodBase" />
			<xs:enumeration value="AnimalisticPersistentThoughtBase" />
			<xs:enumeration value="DefaultReactionBase"/>
			<xs:enumeration value="SapientMemoryBase" />
			<xs:enumeration value="AnimalisticNakedThought" />
			<xs:enumeration value="AnimalisticNakedThougthNudist" />
			<xs:enumeration value="MergedPawnPersistentBase" />
			<xs:enumeration value="SleptThoughtBase" />
		</xs:restriction>
	</xs:simpleType>

	<xs:complexType name="ThoughtStage">
		<xs:all>
			<xs:element name="label" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="labelSocial" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="description" type="xs:string" minOccurs="1" maxOccurs="1" />
			<xs:element name="visible" type="xs:boolean" default="true" minOccurs="0" maxOccurs="1" />
			<xs:element name="baseMoodEffect" type="xs:float" minOccurs="0" maxOccurs="1" />
		</xs:all>
		<xs:attribute name="IsNull" type="xs:boolean" use="optional" />
	</xs:complexType>
</xs:schema>

=== Tachyonite/Pawnmorpher/1.2/Defs/Thoughts/MergedPawns/FH_Persistent.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../Schemas/ThoughtDef.xsd">
	<ThoughtDef Abstract="true" Name="MergedPawnPersistentBase">
		<workerClass>Pawnmorph.Thoughts.Worker_MergedPawn</workerClass>
	</ThoughtDef>

	<ThoughtDef ParentName="MergedPawnPersistentBase">
		<defName>MergedPawnPersistentThoughtDefault</defName>
		<nullifyingTraits>
			<li>BodyPurist</li>
			<li>MutationAffinity</li>
		</nullifyingTraits>
		<stages>
			<li>
				<label>changed</label>
				<description>What on earth?! I can hear you...me...us? I need some space.</description>
				<baseMoodEffect>-5</baseMoodEffect>
			</li>
			<li>
				<label>lingering instinct</label>
				<description>You, stop thinking about it or we're both going to be in trouble.</description>
				<baseMoodEffect>-3</baseMoodEffect>
			</li>
			<li>
				<label>conflicted minds</label>
				<description>C'mon, stop acting like this...I can't think clearly.</description>
				<baseMoodEffect>-1</baseMoodEffect>
			</li>
			<li>
				<label>hard to think...</label>
				<description>You're...making this worse for both of us...we...I need to sleep.</description>
			</li>
			<li>
				<label>feral animal</label>
				<description>...food?</description>
				<baseMoodEffect>5</baseMoodEffect>
			</li>
			<li>
				<label>...</label>
				<description>Food!</description>
			</li>
		</stages>
		<modExtensions>
			<li Class="Pawnmorph.DefExtensions.AspectRestriction">
				<invert>true</invert>
				<aspectEntries>
					<li>
						<aspectDef>PrimalWish</aspectDef>
					</li>
				</aspectEntries>
			</li>
		</modExtensions>
	</ThoughtDef>

	<ThoughtDef ParentName="MergedPawnPersistentBase">
		<defName>MergedPawnPersistentThoughtMA</defName> <!-- mutation affinity -->
		<requiredTraits>
			<li>MutationAffinity</li>
		</requiredTraits>
		<stages>
			<li>
				<label>changed</label>
				<description>Hey friend, I don't know how you feel about this but I think it's pretty cool.</description>
				<baseMoodEffect>1</baseMoodEffect>
			</li>
			<li>
				<label>lingering instinct</label>
				<description>Hmm...we could get used to this. What, you don't like that 'we'?</description>
				<baseMoodEffect>2</baseMoodEffect>
			</li>
			<li>
				<label>conflicted minds</label>
				<description>Listen to the call of the wild...you'll feel better about this.</description>
				<baseMoodEffect>4</baseMoodEffect>
			</li>
			<li>
				<label>hard to think...</label>
				<description>My other mind wants to stay focused...but I want to enjoy the instinct...just become 'I'.</description>
				<baseMoodEffect>6</baseMoodEffect>
			</li>
			<li>
				<label>feral animal</label>
				<description>...food?</description>
			</li>
			<li>
				<label>...</label>
				<description>Food!</description>
			</li>
		</stages>
		<modExtensions>
			<li Class="Pawnmorph.DefExtensions.AspectRestriction">
				<invert>true</invert>
				<aspectEntries>
					<li>
						<aspectDef>PrimalWish</aspectDef>
					</li>
				</aspectEntries>
			</li>
		</modExtensions>
	</ThoughtDef>

	<ThoughtDef ParentName="MergedPawnPersistentBase">
		<defName>MergedPawnPersistentThoughtBP</defName> <!-- body purist-->
		<requiredTraits>
			<li>BodyPurist</li>
		</requiredTraits>
		<stages>
			<li>
				<label>changed</label>
				<description>This is the worst thing I can imagine, welded to someone else in a freakish body!</description>
				<baseMoodEffect>-30</baseMoodEffect>
			</li>
			<li>
				<label>lingering instinct</label>
				<description>Don't think about it! You're making me feel worse!</description>
				<baseMoodEffect>-20</baseMoodEffect>
			</li>
			<li>
				<label>conflicted mind</label>
				<description>My other mind...wants to give in...but I can't!</description>
				<baseMoodEffect>-15</baseMoodEffect>
			</li>
			<li>
				<label>hard to think...</label>
				<description>Gotta...keep...going...but...can't...</description>
				<baseMoodEffect>-5</baseMoodEffect>
			</li>
			<li>
				<label>feral animal</label>
				<description>...food?</description>
			</li>
			<li>
				<label>...</label>
				<description>Food!</description>
			</li>
		</stages>
	</ThoughtDef>

	<ThoughtDef ParentName="MergedPawnPersistentBase">
		<defName>MergedPawnPersistentThoughtPW</defName> <!-- primal wish -->
		<stages>
			<li>
				<label>primal wish fulfilled</label>
				<description>This is...amazing. Hey, second-head, want to be friends?</description>
				<baseMoodEffect>10</baseMoodEffect>
			</li>
			<li>
				<label>lingering instinct</label>
				<description>We're enjoying this feeling...or at least, I think second-head is.</description>
				<baseMoodEffect>15</baseMoodEffect>
			</li>
			<li>
				<label>conflicted minds</label>
				<description>I'm confused, is it 'we' or 'I'? I could use either...</description>
				<baseMoodEffect>10</baseMoodEffect>
			</li>
			<li>
				<label>hard to think...</label>
				<description>Might...just...give...in...sorry other-head.</description>
				<baseMoodEffect>5</baseMoodEffect>
			</li>
			<li>
				<label>feral animal</label>
				<description>...food?</description>
			</li>
			<li>
				<label>...</label>
				<description>Food!</description>
			</li>
		</stages>
		<modExtensions>
			<li Class="Pawnmorph.DefExtensions.AspectRestriction">
				<aspectEntries>
					<li>
						<aspectDef>PrimalWish</aspectDef>
					</li>
				</aspectEntries>
			</li>
		</modExtensions>
	</ThoughtDef>
</Defs>

=== Tachyonite/Pawnmorpher/1.6/Defs/MorphsAndMutationDefs/Animal/PawFooted/Carnivora/Canid/Familiaris/Familiaris_Memories.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../../../Schemas/ThoughtDef.xsd">
	<ThoughtDef ParentName="OutlookMemoryBase">
		<defName>FamiliarisTransformationMemory</defName>
		<stages>
			<li>
				<label>changed</label>
				<description>So I'm the pet dog now? ...arf?</description>
				<baseMoodEffect>-3</baseMoodEffect>
			</li>
			<li>
				<label>changed</label>
				<description>Did somebody say 'belly rub'?</description>
				<baseMoodEffect>+3</baseMoodEffect>
			</li>
			<li>
				<label>changed</label>
				<description>They keep telling me 'fetch'...but I'm not a damn dog!</description>
				<baseMoodEffect>-5</baseMoodEffect>
			</li>
			<li>
				<label>changed</label>
				<description>Fetch?! Where!?</description>
				<baseMoodEffect>+1</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>

	<ThoughtDef ParentName="OutlookMemoryBase">
		<defName>FamiliarisRevertedMemory</defName>
		<stages>
			<li>
				<label>reverted</label>
				<description>Phew... I was having a bit too much fun.</description>
				<baseMoodEffect>3</baseMoodEffect>
			</li>
			<li>
				<label>reverted</label>
				<description>I'm not as peppy as I used to be.</description>
				<baseMoodEffect>-3</baseMoodEffect>
			</li>
			<li>
				<label>reverted</label>
				<description>I'm not a stinky dog anymore!</description>
				<baseMoodEffect>10</baseMoodEffect>
			</li>
			<li>
				<label>reverted</label>
				<description>No more napping on laps for me.</description>
				<baseMoodEffect>-5</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>

	<ThoughtDef ParentName="OutlookMemoryBase">
		<durationDays>1</durationDays>
		<defName>EtherFamiliarisJaw</defName>
		<stages>
			<li>
				<label>dog face</label>
				<description>I just need to pant all the time...</description>
				<visible>true</visible>
				<baseMoodEffect>1</baseMoodEffect>
			</li>
			<li>
				<label>dog face</label>
				<description>BARK BARK BARK!</description>
				<visible>true</visible>
				<baseMoodEffect>3</baseMoodEffect>
			</li>
			<li>
				<label>dog face</label>
				<description>I can't be sad with this smile...</description>
				<visible>true</visible>
				<baseMoodEffect>0</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>

	<ThoughtDef ParentName="OutlookMemoryBase">
		<durationDays>1</durationDays>
		<defName>EtherFamiliarisEar</defName>
		<stages>
			<li>
				<label>dog ears</label>
				<description>They're pretty cute, I gotta say.</description>
				<visible>true</visible>
				<baseMoodEffect>0</baseMoodEffect>
			</li>
			<li>
				<label>dog ears</label>
				<description>They look cute, and I can hear better than before. A win-win!</description>
				<visible>true</visible>
				<baseMoodEffect>2</baseMoodEffect>
			</li>
			<li>
				<label>dog ears</label>
				<description>I want my own ears back, give them BARK!</description>
				<visible>true</visible>
				<baseMoodEffect>-2</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>

	<ThoughtDef ParentName="OutlookMemoryBase">
		<durationDays>1</durationDays>
		<defName>EtherFamiliarisTail</defName>
		<stages>
			<li>
				<label>dog tail</label>
				<description>I gotta calm down, it keeps wagging...</description>
				<visible>true</visible>
				<baseMoodEffect>-1</baseMoodEffect>
			</li>
			<li>
				<label>dog tail</label>
				<description>I'm so excited, it's wagging so fast!</description>
				<visible>true</visible>
				<baseMoodEffect>1</baseMoodEffect>
			</li>
			<li>
				<label>dog tail</label>
				<description>Why do I have to ruin all my pants for a tail that won't stop wagging?</description>
				<visible>true</visible>
				<baseMoodEffect>-2</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>

</Defs>

=== Tachyonite/Pawnmorpher/1.4/Defs/MorphsAndMutationDefs/Animal/PawFooted/Carnivora/Feline/BigFelis/Lynx/Lynx_Memories.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../../../../Schemas/ThoughtDef.xsd">
    <ThoughtDef ParentName="OutlookMemoryBase">
		<defName>LynxTransformationMemory</defName>
        <stages>
            <li>
                <label>changed</label>
                <description>I'm a... cat? What.</description>
                <baseMoodEffect>-3</baseMoodEffect>
            </li>
            <li>
                <label>changed</label>
                <description>I'm not just a regular cat, I'm a cool-looking lynx!</description>
                <baseMoodEffect>+3</baseMoodEffect>
            </li>
            <li>
                <label>changed</label>
                <description>Ugh! Hairball! Disgusting!</description>
                <baseMoodEffect>-5</baseMoodEffect>
            </li>
            <li>
                <label>changed</label>
                <description>I think I want to go out and hunt mice.</description>
                <baseMoodEffect>+1</baseMoodEffect>
            </li>
        </stages>
    </ThoughtDef>

    <ThoughtDef ParentName="OutlookMemoryBase">
		<defName>LynxRevertedMemory</defName>
        <stages>
            <li>
                <label>reverted</label>
                <description>That fur was getting stuffy... and I shed too much.</description>
                <baseMoodEffect>3</baseMoodEffect>
            </li>
            <li>
                <label>reverted</label>
                <description>But I looked so cool!</description>
                <baseMoodEffect>-3</baseMoodEffect>
            </li>
            <li>
                <label>reverted</label>
                <description>No more hairballs! Thank goodness!</description>
                <baseMoodEffect>10</baseMoodEffect>
            </li>
            <li>
                <label>reverted</label>
                <description>This isn't what I wanted.</description>
                <baseMoodEffect>-5</baseMoodEffect>
            </li>
        </stages>
    </ThoughtDef>
	
</Defs>

=== Tachyonite/Pawnmorpher/1.3/Defs/MorphsAndMutationDefs/Animal/Ungulate/EvenToedUngulate/Cervid/BigCervid/Elk/Elk_Memories.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../../../../Schemas/ThoughtDef.xsd">
	<ThoughtDef ParentName="OutlookMemoryBase">
		<defName>ElkTransformationMemory</defName>
				<stages>
						<li>
								<label>Became elk morph</label>
								<description>Great, now I look like a big, shaggy lump.</description>
								<baseMoodEffect>-3</baseMoodEffect>
						</li>
						<li>
								<label>Became elk morph</label>
								<description>I feel so majestic, so imposing. This is awesome!</description>
								<baseMoodEffect>+3</baseMoodEffect>
						</li>
						<li>
								<label>Became elk morph</label>
								<description>An elk? Isn't that just a big deer? Oh I don't care! Just make it stop!</description>
								<baseMoodEffect>-5</baseMoodEffect>
						</li>
						<li>
								<label>Became elk morph</label>
								<description>A good start, how far can I go?</description>
								<baseMoodEffect>+1</baseMoodEffect>
						</li>
				</stages>
		</ThoughtDef>
	
	<ThoughtDef ParentName="OutlookMemoryBase">
		<defName>ElkRevertedMemory</defName>
				<stages>
						<li>
								<label>Reverted</label>
								<description>It's me, I'm back!</description>
								<baseMoodEffect>3</baseMoodEffect>
						</li>
						<li>
								<label>Reverted</label>
								<description>No! My magesty!</description>
								<baseMoodEffect>-3</baseMoodEffect>
						</li>
						<li>
								<label>Reverted</label>
								<description>Oh the humanity! MY humanity! Yay!</description>
								<baseMoodEffect>10</baseMoodEffect>
						</li>
						<li>
								<label>Reverted</label>
								<description>But I was so close to perfection...</description>
								<baseMoodEffect>-5</baseMoodEffect>
						</li>
				</stages>
		</ThoughtDef>

	<ThoughtDef ParentName="OutlookMemoryBase">
			<durationDays>1</durationDays>
			<defName>EtherElkJaw</defName>
			<stages>
					<li>
							<label>Elk face</label>
							<description>I can barely talk with this thing...</description>
							<visible>true</visible>
							<baseMoodEffect>-1</baseMoodEffect>
					</li>
					<li>
							<label>Elk face</label>
							<description>...This is kinda cool, I guess?</description>
							<visible>true</visible>
							<baseMoodEffect>2</baseMoodEffect>
					</li>
					<li>
							<label>Elk face</label>
							<description>What happened to my face?!?</description>
							<visible>true</visible>
							<baseMoodEffect>-3</baseMoodEffect>
					</li>
			</stages>
	</ThoughtDef>

	<ThoughtDef ParentName="OutlookMemoryBase">
		<durationDays>1</durationDays>
		<defName>EtherElkEar</defName>
		<stages>
			<li>
				<label>Elk ears</label>
				<description>Will they ever stop itching?</description>
				<visible>true</visible>
				<baseMoodEffect>-1</baseMoodEffect>
			</li>
			<li>
				<label>Elk ears</label>
				<description>I can hear so well now!</description>
				<visible>true</visible>
				<baseMoodEffect>1</baseMoodEffect>
			</li>
			<li>
				<label>Elk ears</label>
				<description>These things are so twitchy, get them off me!</description>
				<visible>true</visible>
				<baseMoodEffect>-2</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>
	
	<ThoughtDef ParentName="OutlookMemoryBase">
		<durationDays>1</durationDays>
		<defName>EtherElkTail</defName>
		<stages>
			<li>
				<label>Elk tail</label>
				<description>Is this stubby little thing...a tail?</description>
				<visible>true</visible>
				<baseMoodEffect>-1</baseMoodEffect>
			</li>
			<li>
				<label>Elk tail</label>
				<description>It's so small and fluffy!</description>
				<visible>true</visible>
				<baseMoodEffect>1</baseMoodEffect>
			</li>
			<li>
				<label>Elk tail</label>
				<description>At least I can hide it.</description>
				<visible>true</visible>
				<baseMoodEffect>-2</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>
	
		<ThoughtDef ParentName="OutlookMemoryBase">
		<durationDays>1</durationDays>
		<defName>EtherElkAntlers</defName>
		<stages>
			<li>
				<label>Antlers</label>
				<description>How am I supposed to rest on my pillow?</description>
				<visible>true</visible>
				<baseMoodEffect>-1</baseMoodEffect>
			</li>
			<li>
				<label>Antlers</label>
				<description>Behold! Are they not impressive?</description>
				<visible>true</visible>
				<baseMoodEffect>2</baseMoodEffect>
			</li>
			<li>
				<label>Antlers</label>
				<description>These things are horrible. I'm so top heavy now I can hardly walk in a straight line.</description>
				<visible>true</visible>
				<baseMoodEffect>-3</baseMoodEffect>
			</li>
			<li>
				<label>Antlers</label>
				<description>With these, I'd be right at home in the forest.</description>
				<visible>true</visible>
				<baseMoodEffect>1</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>
</Defs>

=== Tachyonite/Pawnmorpher/1.6/Defs/Thoughts/Thoughts_Production.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../Schemas/ThoughtDef.xsd">
	<ThoughtDef>
		<defName>ProductiveBliss</defName>
		<durationDays>0.2</durationDays>
		<stages>
			<li>
				<label>productive bliss</label>
				<description>Can't think...feeling so good...</description>
				<baseMoodEffect>+50</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>

	<!--Egglayer-->
	<ThoughtDef>
		<defName>LaidEgg</defName>
		<durationDays>0.2</durationDays>
		<stages>
			<li>
				<label>laid an egg</label>
				<description>This is humiliating...and it doesn't feel like it'll be the last.</description>
				<baseMoodEffect>-10</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>

	<ThoughtDef>
		<defName>LaidEggMale</defName>
		<durationDays>0.2</durationDays>
		<stages>
			<li>
				<label>laid an egg</label>
				<description>This is humiliating...how does this even work?</description>
				<baseMoodEffect>-20</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>

	<ThoughtDef>
		<defName>LaidEggBond</defName>
		<durationDays>0.2</durationDays>
		<stages>
			<li>
				<label>laid an egg</label>
				<description>Egg...! Bok bwark!</description>
				<baseMoodEffect>+10</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>

	<ThoughtDef>
		<defName>LaidEggBroken</defName>
		<durationDays>0.2</durationDays>
		<stages>
			<li>
				<label>laid an egg</label>
				<description>B..bok...egg...gh..bwark...</description>
				<baseMoodEffect>-1</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>

	<!--Udder-->
	<ThoughtDef>
		<defName>MilkedMyself</defName>
		<durationDays>1</durationDays>
		<stages>
			<li>
				<label>milked myself</label>
				<description>I'm so embarrased.</description>
				<baseMoodEffect>-10</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>
	<ThoughtDef>
		<defName>MilkedMyselfMale</defName>
		<durationDays>1</durationDays>
		<stages>
			<li>
				<label>milked myself</label>
				<description>For the love of...not milk!</description>
				<baseMoodEffect>-20</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>

	<ThoughtDef>
		<defName>MilkedMyselfBond</defName>
		<durationDays>0.2</durationDays>
		<stages>
			<li>
				<label>milked myself</label>
				<description>Mmmmooooooo!</description>
				<baseMoodEffect>+10</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>

	<ThoughtDef>
		<defName>MilkedMyselfBroken</defName>
		<durationDays>0.2</durationDays>
		<stages>
			<li>
				<label>milked myself</label>
				<description>Mm..mooo...mmilk...?</description>
				<baseMoodEffect>-1</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>

	<!--Chemical Udder-->
	<ThoughtDef>
		<defName>ChemMilkedMyself</defName>
		<durationDays>1</durationDays>
		<stages>
			<li>
				<label>drained my chemcyst</label>
				<description>This is disgusting.</description>
				<baseMoodEffect>-10</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>

	<ThoughtDef>
		<defName>ChemMilkedMyselfBond</defName>
		<durationDays>0.2</durationDays>
		<stages>
			<li>
				<label>drained my chemcyst</label>
				<description>Boom!</description>
				<baseMoodEffect>+10</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>

	<ThoughtDef>
		<defName>ChemMilkedMyselfBroken</defName>
		<durationDays>0.2</durationDays>
		<stages>
			<li>
				<label>drained my chemcyst</label>
				<description>B...boom...b..oom?</description>
				<baseMoodEffect>-1</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>

	<!--Wooly-->
	<ThoughtDef>
		<defName>ShavedMyself</defName>
		<durationDays>1</durationDays>
		<stages>
			<li>
				<label>shaved myself</label>
				<description>That was a lot of hair. I hope this ends soon.</description>
				<baseMoodEffect>-5</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>

	<ThoughtDef>
		<defName>ShavedMyselfBond</defName>
		<durationDays>1</durationDays>
		<stages>
			<li>
				<label>clean shaven</label>
				<description>It's weird, but it feels kinda good to shave all that wool off.</description>
				<baseMoodEffect>5</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>

	<ThoughtDef>
		<defName>ShavedMyselfBroken</defName>
		<durationDays>1</durationDays>
		<stages>
			<li>
				<label>shaved myself... again</label>
				<description>This will end, right?</description>
				<baseMoodEffect>-1</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>

	<!--Pig/Boar Snout-->
	<ThoughtDef>
		<defName>FoundTruffles</defName>
		<durationDays>0.5</durationDays>
		<stages>
			<li>
				<label>found truffles</label>
				<description>I managed to find some food while sniffing around in the dirt. Kinda dirty, but tasty.</description>
				<baseMoodEffect>5</baseMoodEffect>
			</li>
		</stages>
	</ThoughtDef>
</Defs>

=== Tachyonite/Pawnmorpher/1.6/Defs/MorphsAndMutationDefs/Animal/Avian/Anserigalliform/Galliform/Goose/Goose_Memories.xml
<Defs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../../../../../../Schemas/ThoughtDef.xsd">
    <ThoughtDef ParentName="OutlookMemoryBase">
		<defName>GooseTransformationMemory</defName>
        <stages>
            <li>
                <label>morphed</label>
                <description>I'm- HONK! covered in feathers- HONK!</description>
                <baseMoodEffect>-3</baseMoodEffect>
            </li>
            <li>
              <label>morphed</label>
                <description>I think I could tie up this look with a red bow around my neck.</description>
                <baseMoodEffect>+3</baseMoodEffect>
            </li>
            <li>
              <label>morphed</label>
                <description>Change me back! I- HONK! -ing hate geese!</description>
                <baseMoodEffect>-5</baseMoodEffect>
            </li>
            <li>
              <label>morphed</label>
                <description>Honk! Honk honk!</description>
                <baseMoodEffect>+1</baseMoodEffect>
            </li>
        </stages>
    </ThoughtDef>

    <ThoughtDef ParentName="OutlookMemoryBase">
		<defName>GooseRevertedMemory</defName>
        <stages>
            <li>
                <label>reverted</label>
                <description>I'm back to my normal, human self again! No more feathers...</description>
                <baseMoodEffect>3</baseMoodEffect>
            </li>
            <li>
                <label>reverted</label>
                <description>But the feathers! My beak! I would have preferred to stay that way.</description>
                <baseMoodEffect>-3</baseMoodEffect>
            </li>
            <li>
                <label>reverted</label>
                <description>Hands at last. I'd prefer not to be a demon-spawn bird.</description>
                <baseMoodEffect>10</baseMoodEffect>
            </li>
            <li>
                <label>reverted</label>
                <description>I'm human again? I think I wanted the opposite of this.</description>
                <baseMoodEffect>-5</baseMoodEffect>
            </li>
        </stages>
    </ThoughtDef>
</Defs>
